package net.grey3345.gkIronmod.util;

import net.grey3345.gkIronmod.block.ModBlocks;
import net.minecraft.world.level.block.Block;

import javax.annotation.Nullable;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

public class RustStateMap {


    private static final Map<Block, Block> INCREASES = new HashMap<>();

    private static final Map<Block, Block> DECREASES = new HashMap<>();

    private static final Map<Block, Block> WAXED = new HashMap<>();

    private static final Map<Block, Block> UNWAXED = new HashMap<>();

    public static void put(Block block, @Nullable Block oxidized, Block waxed) {
        if (oxidized != null) {
            INCREASES.put(block, oxidized);
            DECREASES.put(oxidized, block);
        }
        WAXED.put(block, waxed);
        UNWAXED.put(waxed, block);
    }

    public static Optional<Block> getIncrease(Block block) {
        return Optional.ofNullable(INCREASES.get(block));
    }

    public static Optional<Block> getDecrease(Block block) {
        return Optional.ofNullable(DECREASES.get(block));
    }

    public static Optional<Block> getWaxed(Block block) {
        return Optional.ofNullable(WAXED.get(block));
    }

    public static Optional<Block> getUnwaxed(Block block) { return Optional.ofNullable(UNWAXED.get(block)); }

    public static Block getOriginalStage(Block block) {
        var result = block;
        for (var b = getDecrease(block); b.isPresent(); b = getDecrease(b.get())) {
            result = b.get();
        }
        return result;
    }

    static {
        put(ModBlocks.RAW_WROUGHT_IRON_BLOCK.get(), ModBlocks.RAW_WROUGHT_IRON_BLOCK_EXPOSED.get(), ModBlocks.RAW_WROUGHT_IRON_BLOCK_WAXED.get());
        put(ModBlocks.RAW_WROUGHT_IRON_BLOCK_EXPOSED.get(), ModBlocks.RAW_WROUGHT_IRON_BLOCK_WEATHERED.get(), ModBlocks.RAW_WROUGHT_IRON_BLOCK_EXPOSED_WAXED.get());
        put(ModBlocks.RAW_WROUGHT_IRON_BLOCK_WEATHERED.get(), ModBlocks.RAW_WROUGHT_IRON_BLOCK_RUSTED.get(), ModBlocks.RAW_WROUGHT_IRON_BLOCK_WEATHERED_WAXED.get());
        put(ModBlocks.RAW_WROUGHT_IRON_BLOCK_RUSTED.get(), null, ModBlocks.RAW_WROUGHT_IRON_BLOCK_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK.get(), ModBlocks.WROUGHT_IRON_BLOCK_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_STAIRS.get(), ModBlocks.WROUGHT_IRON_BLOCK_STAIRS_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_STAIRS_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_STAIRS_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_STAIRS_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_STAIRS_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_STAIRS_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_STAIRS_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_STAIRS_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_STAIRS_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_STAIRS_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_SLAB.get(), ModBlocks.WROUGHT_IRON_BLOCK_SLAB_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_SLAB_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_SLAB_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_SLAB_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_SLAB_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_SLAB_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_SLAB_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_SLAB_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_SLAB_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_SLAB_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_WALL.get(), ModBlocks.WROUGHT_IRON_BLOCK_WALL_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_WALL_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_WALL_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_WALL_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_WALL_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_WALL_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_WALL_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_WALL_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_WALL_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_WALL_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_BARS.get(), ModBlocks.WROUGHT_IRON_BLOCK_BARS_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_BARS_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_BARS_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_BARS_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_BARS_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_BARS_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_BARS_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_BARS_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_BARS_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_BARS_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_BEAMS.get(), ModBlocks.WROUGHT_IRON_BLOCK_BEAMS_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_BEAMS_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_BEAMS_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_BEAMS_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_BEAMS_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_BEAMS_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_BEAMS_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_BEAMS_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_BEAMS_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_BEAMS_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CHISELLED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CHISELLED_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CHISELLED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CHISELLED_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CHISELLED_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CHISELLED_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CHISELLED_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CHISELLED_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CHISELLED_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CHISELLED_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_CHISELLED_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PILLAR.get(), ModBlocks.WROUGHT_IRON_BLOCK_PILLAR_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PILLAR_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PILLAR_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PILLAR_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PILLAR_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PILLAR_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PILLAR_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PILLAR_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PILLAR_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_PILLAR_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_PLATED_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED_STAIRS.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_STAIRS_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_STAIRS_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED_STAIRS_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_STAIRS_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_STAIRS_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED_STAIRS_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_STAIRS_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_STAIRS_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED_STAIRS_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_PLATED_STAIRS_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED_SLAB.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_SLAB_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_SLAB_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED_SLAB_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_SLAB_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_SLAB_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED_SLAB_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_SLAB_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_SLAB_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED_SLAB_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_PLATED_SLAB_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED_WALL.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_WALL_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_WALL_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED_WALL_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_WALL_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_WALL_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED_WALL_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_WALL_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_PLATED_WALL_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_PLATED_WALL_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_PLATED_WALL_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_CUT_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_STAIRS.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_STAIRS_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_STAIRS_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_STAIRS_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_STAIRS_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_STAIRS_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_STAIRS_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_STAIRS_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_STAIRS_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_STAIRS_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_CUT_STAIRS_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_SLAB.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_SLAB_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_SLAB_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_SLAB_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_SLAB_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_SLAB_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_SLAB_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_SLAB_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_SLAB_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_SLAB_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_CUT_SLAB_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_WALL.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_WALL_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_WALL_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_WALL_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_WALL_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_WALL_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_WALL_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_WALL_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_WALL_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_WALL_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_CUT_WALL_RUSTED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_BEAM.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_BEAM_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_BEAM_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_BEAM_EXPOSED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_BEAM_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_BEAM_EXPOSED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_BEAM_WEATHERED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_BEAM_RUSTED.get(), ModBlocks.WROUGHT_IRON_BLOCK_CUT_BEAM_WEATHERED_WAXED.get());
        put(ModBlocks.WROUGHT_IRON_BLOCK_CUT_BEAM_RUSTED.get(), null, ModBlocks.WROUGHT_IRON_BLOCK_CUT_BEAM_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_STAIRS.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_STAIRS_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_STAIRS_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_STAIRS_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_STAIRS_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_STAIRS_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_STAIRS_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_STAIRS_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_STAIRS_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_STAIRS_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_STAIRS_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_SLAB.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_SLAB_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_SLAB_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_SLAB_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_SLAB_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_SLAB_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_SLAB_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_SLAB_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_SLAB_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_SLAB_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_SLAB_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_WALL.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_WALL_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_WALL_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_WALL_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_WALL_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_WALL_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_WALL_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_WALL_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_WALL_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_WALL_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_WALL_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BARS.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BARS_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BARS_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BARS_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BARS_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BARS_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BARS_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BARS_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BARS_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BARS_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BARS_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BEAMS.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BEAMS_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BEAMS_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BEAMS_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BEAMS_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BEAMS_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BEAMS_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BEAMS_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BEAMS_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BEAMS_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_BEAMS_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CHISELLED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CHISELLED_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CHISELLED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CHISELLED_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CHISELLED_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CHISELLED_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CHISELLED_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CHISELLED_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CHISELLED_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CHISELLED_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CHISELLED_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PILLAR.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PILLAR_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PILLAR_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PILLAR_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PILLAR_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PILLAR_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PILLAR_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PILLAR_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PILLAR_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PILLAR_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PILLAR_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_STAIRS.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_STAIRS_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_STAIRS_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_STAIRS_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_STAIRS_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_STAIRS_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_STAIRS_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_STAIRS_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_STAIRS_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_STAIRS_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_STAIRS_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_SLAB.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_SLAB_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_SLAB_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_SLAB_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_SLAB_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_SLAB_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_SLAB_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_SLAB_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_SLAB_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_SLAB_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_SLAB_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_WALL.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_WALL_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_WALL_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_WALL_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_WALL_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_WALL_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_WALL_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_WALL_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_WALL_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_WALL_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_PLATED_WALL_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_STAIRS.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_STAIRS_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_STAIRS_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_STAIRS_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_STAIRS_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_STAIRS_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_STAIRS_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_STAIRS_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_STAIRS_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_STAIRS_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_STAIRS_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_SLAB.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_SLAB_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_SLAB_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_SLAB_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_SLAB_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_SLAB_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_SLAB_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_SLAB_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_SLAB_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_SLAB_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_SLAB_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_WALL.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_WALL_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_WALL_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_WALL_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_WALL_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_WALL_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_WALL_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_WALL_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_WALL_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_WALL_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_WALL_RUSTED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_BEAM.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_BEAM_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_BEAM_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_BEAM_EXPOSED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_BEAM_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_BEAM_EXPOSED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_BEAM_WEATHERED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_BEAM_RUSTED.get(), ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_BEAM_WEATHERED_WAXED.get());
        put(ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_BEAM_RUSTED.get(), null, ModBlocks.REFINED_WROUGHT_IRON_BLOCK_CUT_BEAM_RUSTED_WAXED.get());
    }
}